"""add vehicle_id to driver_schedule

Revision ID: 3c4b96548625
Revises: 80a2ef4e3635
Create Date: 2026-02-26 20:07:23.021377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4b96548625'
down_revision: Union[str, None] = '80a2ef4e3635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_schedule', sa.Column('vehicle_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_driver_schedule_vehicle_id'), 'driver_schedule', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'driver_schedule', 'vehicle', ['vehicle_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'driver_schedule', type_='foreignkey')
    op.drop_index(op.f('ix_driver_schedule_vehicle_id'), table_name='driver_schedule')
    op.drop_column('driver_schedule', 'vehicle_id')
    # ### end Alembic commands ###
