"""driverschedule

Revision ID: 80a2ef4e3635
Revises: f51bb1e38271
Create Date: 2026-02-26 06:25:51.285702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80a2ef4e3635'
down_revision: Union[str, None] = 'f51bb1e38271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('arrive_by_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='ck_day_of_week'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'day_of_week', 'arrive_by_time', name='uq_driver_schedule_slot')
    )
    op.create_index(op.f('ix_driver_schedule_driver_id'), 'driver_schedule', ['driver_id'], unique=False)
    op.add_column('driver', sa.Column('route_polyline', sa.Text(), nullable=True))
    op.drop_column('driver', 'route_public')
    op.add_column('ride', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.add_column('ride', sa.Column('service_date', sa.Date(), nullable=False))
    op.add_column('ride', sa.Column('arrive_by_time', sa.Time(), nullable=False))
    op.drop_index('ix_ride_departure_time', table_name='ride')
    op.create_index(op.f('ix_ride_schedule_id'), 'ride', ['schedule_id'], unique=False)
    op.create_unique_constraint('uq_ride_schedule_id', 'ride', ['schedule_id', 'service_date'])
    op.create_foreign_key(None, 'ride', 'driver_schedule', ['schedule_id'], ['id'], ondelete='SET NULL')
    op.drop_column('ride', 'departure_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('departure_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ride', type_='foreignkey')
    op.drop_constraint('uq_ride_schedule_id', 'ride', type_='unique')
    op.drop_index(op.f('ix_ride_schedule_id'), table_name='ride')
    op.create_index('ix_ride_departure_time', 'ride', ['departure_time'], unique=False)
    op.drop_column('ride', 'arrive_by_time')
    op.drop_column('ride', 'service_date')
    op.drop_column('ride', 'schedule_id')
    op.add_column('driver', sa.Column('route_public', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('driver', 'route_polyline')
    op.drop_index(op.f('ix_driver_schedule_driver_id'), table_name='driver_schedule')
    op.drop_table('driver_schedule')
    # ### end Alembic commands ###
