"""init schema

Revision ID: f51bb1e38271
Revises: 
Create Date: 2026-02-23 03:34:05.081543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51bb1e38271'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('drives_count', sa.Integer(), nullable=False),
    sa.Column('route_start_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('route_start_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('route_public', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('seats >= 1 AND seats <= 8', name='ck_vehicle_seats_range'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'plate', name='uq_vehicle_driver_plate')
    )
    op.create_index(op.f('ix_vehicle_driver_id'), 'vehicle', ['driver_id'], unique=False)
    op.create_table('ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'started', 'completed', 'cancelled', name='ridestatus'), nullable=False),
    sa.Column('seats_available', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cost >= 0', name='ck_ride_cost_nonneg'),
    sa.CheckConstraint('seats_available >= 0', name='ck_ride_seats_available_nonneg'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_departure_time'), 'ride', ['departure_time'], unique=False)
    op.create_index(op.f('ix_ride_driver_id'), 'ride', ['driver_id'], unique=False)
    op.create_index(op.f('ix_ride_vehicle_id'), 'ride', ['vehicle_id'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('booked', 'cancelled', 'completed', 'no_show', name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('pickup_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.CheckConstraint('seats >= 1', name='ck_booking_seats_pos'),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_id'], ['rider.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id', 'rider_id', name='uq_booking_ride_rider')
    )
    op.create_index(op.f('ix_booking_ride_id'), 'booking', ['ride_id'], unique=False)
    op.create_index(op.f('ix_booking_rider_id'), 'booking', ['rider_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('safety', 'harassment', 'fraud', 'no_show', 'driving', 'other', name='reportreason'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_id'], ['rider.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_driver_id'), 'report', ['driver_id'], unique=False)
    op.create_index(op.f('ix_report_ride_id'), 'report', ['ride_id'], unique=False)
    op.create_index(op.f('ix_report_rider_id'), 'report', ['rider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_rider_id'), table_name='report')
    op.drop_index(op.f('ix_report_ride_id'), table_name='report')
    op.drop_index(op.f('ix_report_driver_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_booking_rider_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_ride_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_ride_vehicle_id'), table_name='ride')
    op.drop_index(op.f('ix_ride_driver_id'), table_name='ride')
    op.drop_index(op.f('ix_ride_departure_time'), table_name='ride')
    op.drop_table('ride')
    op.drop_index(op.f('ix_vehicle_driver_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_table('rider')
    op.drop_table('driver')
    # ### end Alembic commands ###
